on: 
  push:
    branches:
    - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:

        server: ftp.hyperphp.com
        username: hp_32992025
        password: ${{ secrets.FTP_PASS }}  
        server-dir: htdocs/ 
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          vendor/*
          app/cache/*
          writable/session/*
          app/Config/Boot/*
          app/Config/*        
          app/core/*
          app/helpers/*
          app/hooks/*
          app/language/**
          app/libraries/*
          app/logs/*
          app/third_party/*
          writable/debugbar/*
          .env
